server:
  port: 9090

#??MySql?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #??MySql?url
    url: jdbc:mysql://110.42.189.226:3306/UUJob?serverTimezone=GMT%2b8
    #?????????
    username: xxy
    #????
    password: xxy123

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  check-config-location:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


    mvc:
        path match:
          matching-strategy: ant_path_matcher